// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Mission06_chanse99.Models;

namespace Mission06_chanse99.Migrations
{
    [DbContext(typeof(MovieCollectionContext))]
    [Migration("20230213205023_Initial")]
    partial class Initial
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.32");

            modelBuilder.Entity("Mission06_chanse99.Models.MovieResponse", b =>
                {
                    b.Property<int>("MovieId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Director")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<bool>("Edited")
                        .HasColumnType("INTEGER");

                    b.Property<string>("LentTo")
                        .HasColumnType("TEXT");

                    b.Property<string>("MovieTitle")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Notes")
                        .HasColumnType("TEXT")
                        .HasMaxLength(25);

                    b.Property<string>("Rating")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<ushort>("Year")
                        .HasColumnType("INTEGER");

                    b.HasKey("MovieId");

                    b.ToTable("responses");

                    b.HasData(
                        new
                        {
                            MovieId = 1,
                            Category = "Action/Adventure",
                            Director = "Ryan Coogler",
                            Edited = false,
                            LentTo = "",
                            MovieTitle = "Black Panther: Wakanda Forever",
                            Notes = "",
                            Rating = "PG-13",
                            Year = (ushort)2022
                        },
                        new
                        {
                            MovieId = 2,
                            Category = "Adventure/Comedy",
                            Director = "Joel Crawford",
                            Edited = false,
                            LentTo = "",
                            MovieTitle = "Puss in Boots: The Last Wish",
                            Notes = "",
                            Rating = "PG",
                            Year = (ushort)2022
                        },
                        new
                        {
                            MovieId = 3,
                            Category = "Drama/Comedy",
                            Director = "Marc Forster",
                            Edited = false,
                            LentTo = "",
                            MovieTitle = "A Man Called Otto",
                            Notes = "",
                            Rating = "PG-13",
                            Year = (ushort)2022
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
